module.exports = {
  "Charged Strike": require("./Amazon/Charged Strike.json"),
  "Cold Arrow": require("./Amazon/Cold Arrow.json"),
  "Exploding Arrow": require("./Amazon/Exploding Arrow.json"),
  "Fire Arrow": require("./Amazon/Fire Arrow.json"),
  "Freezing Arrow": require("./Amazon/Freezing Arrow.json"),
  "Ice Arrow": require("./Amazon/Ice Arrow.json"),
  "Immolation Arrow": require("./Amazon/Immolation Arrow.json"),
  "Lightning Bolt": require("./Amazon/Lightning Bolt.json"),
  "Lightning Fury": require("./Amazon/Lightning Fury.json"),
  "Lightning Strike": require("./Amazon/Lightning Strike.json"),
  "Magic Arrow": require("./Amazon/Magic Arrow.json"),
  "Plague Javelin": require("./Amazon/Plague Javelin.json"),
  "Poison Javelin": require("./Amazon/Poison Javelin.json"),
  "Power Strike": require("./Amazon/Power Strike.json"),
};
